// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoFindrUserAPI.Infrastructure.Data.AppData;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MotoFindrUserAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250522002927_Corrigindo-Relacionamento")]
    partial class CorrigindoRelacionamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MotoFindrUserAPI.Domain.Entities.MotoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoDeFabricacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("MotoqueiroId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("NVARCHAR2(7)");

                    b.HasKey("Id");

                    b.ToTable("tb_mf_moto");
                });

            modelBuilder.Entity("MotoFindrUserAPI.Domain.Entities.MotoqueiroEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("MotoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("MotoId")
                        .IsUnique()
                        .HasFilter("\"MotoId\" IS NOT NULL");

                    b.ToTable("tb_mf_motoqueiro");
                });

            modelBuilder.Entity("MotoFindrUserAPI.Domain.Entities.MotoqueiroEntity", b =>
                {
                    b.HasOne("MotoFindrUserAPI.Domain.Entities.MotoEntity", "Moto")
                        .WithOne("Motoqueiro")
                        .HasForeignKey("MotoFindrUserAPI.Domain.Entities.MotoqueiroEntity", "MotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("MotoFindrUserAPI.Domain.Entities.MotoEntity", b =>
                {
                    b.Navigation("Motoqueiro");
                });
#pragma warning restore 612, 618
        }
    }
}
